# <font color='red'>Importing </font>
<hr style='border: 2px solid red;'>

In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('./Customer-Churn.txt', sep = ',')

In [4]:
data.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [5]:
data.shape

(7043, 18)

# <font color='red'>Changing variables </font>
<hr style='border: 2px solid red;'>

### <font color = 'green'> manually: </font> 

In [6]:
translate_dic = { 'Sim': 1,
                 'Nao': 0 }

In [7]:
data_modified = data[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(translate_dic)

In [8]:
data_modified.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

### <font color = 'green'> using get_dummies:  </font> 

In [9]:
dummie_data = pd.get_dummies(data.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis = 1))

In [10]:
dummie_data.head()

Maior65Anos  MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0            0                1        29.85                            0   
1            0               34        56.95                            1   
2            0                2        53.85                            1   
3            0               45        42.30                            0   
4            0                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   
3                      1                              0   
4                      0                              1   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  ...  StreamingDeFilmes_Nao  \
0                      0                    1  ...                      1   
1                      0                    0  ...                      1   
2                      0                    0  ...                      1   
3                      0                    0  ...                      1   
4                      0                    1  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 34 columns]

### <font color = 'green'> Putting all Together :  </font>

In [12]:
final_data = pd.concat([data_modified, dummie_data], axis = 1)

In [13]:
final_data.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   
3                                             1  ...                      1   
4                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 39 columns]

In [14]:
final_data.shape

(7043, 39)

# <font color='red'>Definitions  </font>
<hr style='border: 2px solid red;'>

##### to see all the 39 columns: 

In [15]:
pd.set_option('display.max_columns', 39) 

In [16]:
final_data.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   
3                      1                              0   
4                      0                              1   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                      0                    1   
1                      0                    0   
2                      0                    0   
3                      0                    0   
4                      0                    1   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                     0                    0   
1                                     0                    1   
2                                     0                    1   
3                                     0                    1   
4                                     0                    0   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0                 0                                  0                 1   
1                 1                                  0                 0   
2                 0                                  0                 1   
3                 1                                  0                 0   
4                 1                                  0                 0   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                        1                                         0   
1                        0                                         0   
2                        1                                         0   
3                        0                                         0   
4                        1                                         0   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                        0                   1   
1                        1                   1   
2                        0                   1   
3                        1                   0   
4                        0                   1   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                    0                   0            1   
1                                    0                   0            1   
2                                    0                   0            1   
3                                    0                   1            1   
4                                    0                   0         

 **X** = inputs

**Y** = outputs

#### for a new client 'maria': 

In [34]:
x_maria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,1,1]]

In [18]:
# y_maria = ? 

# <font color='red'>Using K-Nearest Neighbors (KNN)</font>
<hr style='border: 2px solid red;'>

#### How it works: 

## <font color='green'>KNN backstage</font>
<hr style='border: 1px solid green;'>

#### inputs and outputs

In [20]:
x = final_data.drop('Churn', axis = 1)

In [21]:
y = final_data['Churn'] 

#### library to padronize the data

In [24]:
from sklearn.preprocessing import StandardScaler

#### <font color = 'red'>  obs.: it's important to put all data at the same scale </font> 

In [25]:
norm = StandardScaler()

In [26]:
x_norm = norm.fit_transform(x)

In [27]:
x_norm

array([[ 1.03453023, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 , -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
        -0.54480692,  1.88720123]])

#### checking the information for the client number [0]

In [28]:
x_norm[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

#### norm x_maria

In [35]:
x_maria_norm = norm.transform(pd.DataFrame(x_maria, columns = x.columns))

In [36]:
x_maria_norm

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322,  1.56387171,
        -0.81475874, -0.52592737, -0.79013171, -0.80874158,  1.90140322,
        -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        -0.71102597,  1.83551265,  1.88720123]])

## <font color='green'>Calculating distance (using Euclidean) </font>
<hr style='border: 1px solid green;'>

In [37]:
import numpy as np

In [38]:
a = x_maria_norm

In [39]:
b = x_norm[0]

In [40]:
# subtracting 

In [41]:
a - b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -0.04072036,  0.3340212 ,  2.00139589, -3.3814487 ,  0.        ,
        -2.10545189,  2.01476153,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.42733059,  0.        , -2.00018971,  2.42733059,  2.20331035,
        -2.04211593,  0.        ,  0.        , -2.0452305 ,  2.42733059,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -2.11744436,  2.38031958,  2.41708643]])

In [42]:
# exponent 

In [43]:
np.square(a-b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.65814802e-03, 1.11570160e-01, 4.00558550e+00,
        1.14341953e+01, 0.00000000e+00, 4.43292768e+00, 4.05926401e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.89193381e+00, 0.00000000e+00, 4.00075888e+00, 5.89193381e+00,
        4.85457649e+00, 4.17023749e+00, 0.00000000e+00, 0.00000000e+00,
        4.18296779e+00, 5.89193381e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.48357062e+00,
        5.66592128e+00, 5.84230682e+00]])

In [44]:
# adding 

In [45]:
np.sum(np.square(a-b))

90.36014841460842

In [46]:
# geting the distance

In [48]:
np.sqrt(90.36014841460842)

9.505795517188892

## <font color='green'>Implementing the model </font>
<hr style='border: 1px solid green;'>

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_training, x_test, y_training, y_test = train_test_split(x_norm, y, test_size = 0.3, random_state = 123)

### Training and test

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
# instanciating the model

In [53]:
knn = KNeighborsClassifier(metric = 'euclidean')

In [55]:
# training the model with the training data

In [54]:
knn.fit(x_training, y_training)

KNeighborsClassifier(metric='euclidean')

In [56]:
#testing the model with the test data

In [57]:
prediction_knn = knn.predict(x_test)

In [58]:
prediction_knn

array([1, 0, 0, ..., 0, 0, 0])

In [71]:
from sklearn.metrics import accuracy_score

In [72]:
accuracy = accuracy_score(y_test, prediction_knn) * 100

In [73]:
print('The accuracy is : %.2f%% ' %accuracy )

The accuracy is : 74.54% 


# <font color='red'>Probabilistic model</font>
<hr style='border: 2px solid red;'>

## <font color='green'>Naive Bayes theorem </font>
<hr style='border: 1px solid green;'>

In [59]:
# selecting median because its our central value 

In [60]:
np.median(x_training)

-0.5259273725834717

In [61]:
# importing Library to Create machine learning model

In [62]:
from sklearn.naive_bayes import BernoulliNB

In [63]:
#creating the model

In [66]:
bnb = BernoulliNB(binarize = -0.52) #above = 1 below = 0

In [67]:
bnb.fit(x_training, y_training)

BernoulliNB(binarize=-0.52)

In [68]:
predict_Bnb = bnb.predict(x_test)

In [69]:
predict_Bnb

array([1, 0, 0, ..., 0, 1, 0])

In [74]:
accuracy = accuracy_score(y_test, predict_Bnb) * 100

In [75]:
print('The accuracy is : %.2f%% ' %accuracy )

The accuracy is : 71.84% 


# <font color='red'>Decision tree</font>
<hr style='border: 2px solid red;'>

In [76]:
# importing 

In [77]:
from sklearn.tree import DecisionTreeClassifier

In [78]:
# instanciating the model

In [79]:
dtc = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)

In [80]:
# training the model

In [81]:
dtc.fit(x_training, y_training)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [82]:
# checking the importance of each attribute

In [83]:
dtc.feature_importances_

array([0.03168742, 0.01862901, 0.00064085, 0.02675693, 0.0208788 ,
       0.2056003 , 0.29546501, 0.0061786 , 0.00273035, 0.00747536,
       0.        , 0.04908356, 0.        , 0.01609395, 0.        ,
       0.00722833, 0.01220706, 0.        , 0.01248286, 0.01138295,
       0.0006673 , 0.0095669 , 0.01841631, 0.        , 0.00650511,
       0.00385849, 0.        , 0.00666929, 0.00517146, 0.        ,
       0.00665371, 0.00473251, 0.15803541, 0.00348686, 0.01414378,
       0.01601964, 0.01064163, 0.01091026])

In [84]:
predict_DecisionTree = dtc.predict(x_test)

In [85]:
predict_DecisionTree

array([1, 0, 0, ..., 1, 0, 0])

In [86]:
accuracy = accuracy_score(y_test, predict_DecisionTree) * 100

In [87]:
print('The accuracy is : %.2f%% ' %accuracy )

The accuracy is : 73.31% 


# <font color='red'>Validating the models</font>
<hr style='border: 2px solid red;'>

## <font color='green'>Confusion matrix </font>
<hr style='border: 1px solid green;'>

In [89]:
# importing

In [90]:
from sklearn.metrics import confusion_matrix

In [94]:
# [VP FN]     VP = verdadeiro position FN = falso negativo
# [FP VN]     FP = falso positivo  VN = verdadeiro negativo

In [91]:
print(confusion_matrix(y_test, prediction_knn))

[[1302  221]
 [ 317  273]]


In [92]:
print(confusion_matrix(y_test, predict_Bnb))

[[1045  478]
 [ 117  473]]


In [93]:
print(confusion_matrix(y_test, predict_DecisionTree))

[[1249  274]
 [ 290  300]]


## <font color='green'>Accuracy  </font>
<hr style='border: 1px solid green;'>

In [95]:
accuracy = accuracy_score(y_test, prediction_knn) * 100

In [96]:
print('The accuracy is : %.2f%% ' %accuracy )

The accuracy is : 74.54% 


In [97]:
accuracy = accuracy_score(y_test, predict_DecisionTree) * 100

In [98]:
print('The accuracy is : %.2f%% ' %accuracy )

The accuracy is : 73.31% 


In [99]:
accuracy = accuracy_score(y_test, predict_Bnb) * 100

In [100]:
print('The accuracy is : %.2f%% ' %accuracy )

The accuracy is : 71.84% 


## <font color='green'>Precision </font>
<hr style='border: 1px solid green;'>

In [101]:
# importing

In [102]:
from sklearn.metrics import precision_score

In [103]:
precision = precision_score(y_test, prediction_knn) * 100

In [104]:
print('The accuracy is : %.2f%% ' %precision )

The accuracy is : 55.26% 


In [105]:
precision = precision_score(y_test, predict_Bnb) * 100

In [106]:
print('The accuracy is : %.2f%% ' %precision )

The accuracy is : 49.74% 


In [107]:
precision = precision_score(y_test, predict_DecisionTree) * 100

In [108]:
print('The accuracy is : %.2f%% ' %precision )

The accuracy is : 52.26% 


## <font color='green'>Recall </font>
<hr style='border: 1px solid green;'>

In [109]:
from sklearn.metrics import recall_score

In [110]:
recall = recall_score(y_test, prediction_knn) * 100

In [111]:
print('The accuracy is : %.2f%% ' %recall )

The accuracy is : 46.27% 


In [112]:
recall = recall_score(y_test, predict_Bnb) * 100

In [113]:
print('The accuracy is : %.2f%% ' %precision )

The accuracy is : 52.26% 


In [114]:
recall = recall_score(y_test, predict_DecisionTree) * 100

In [115]:
print('The accuracy is : %.2f%% ' %precision )

The accuracy is : 52.26% 


# <font color='red'>Choosing the best model</font>
<hr style='border: 2px solid red;'>

In [116]:
# best model based on precision: 

**KNN model**